repos:
  - repo: local
    hooks:
      - id: unittest
        name: unittest
        entry: python3 -m unittest -v _test_sandbox.py
        language: system
        always_run: true
        pass_filenames: false
